In [21]:
import pandas as pd
data = {
    "Sepal Length": [5.1, 4.9, 4.7, 4.6, 5.0, 7.0, 6.4, 6.9, 5.5, 6.5, 6.3, 5.8, 7.1, 6.3, 6.5],
    "Sepal Width": [3.5, 3.0, 3.2, 3.1, 3.6, 3.2, 3.2, 3.1, 2.3, 2.8, 3.3, 2.7, 3.0, 2.9, 3.0],
    "Petal Length": [1.4, 1.4, 1.3, 1.5, 1.4, 4.7, 4.5, 4.9, 4.0, 4.6, 6.0, 5.1, 5.9, 5.6, 5.8],
    "Petal Width": [0.2, 0.2, 0.2, 0.2, 0.2, 1.4, 1.5, 1.5, 1.3, 1.5, 2.5, 1.9, 2.1, 1.8, 2.2],
    "Species": ["Setosa", "Setosa", "Setosa", "Setosa", "Setosa", "Versicolor", "Versicolor", "Versicolor", "Versicolor", "Versicolor", "Virginica", "Virginica", "Virginica", "Virginica", "Virginica"]
}
df = pd.DataFrame(data)
df.to_csv("iris_dataset.csv", index=False)
print("CSV file 'iris_dataset.csv' has been generated.")

CSV file 'iris_dataset.csv' has been generated.

In [22]:
df = pd.read_csv("iris_dataset.csv")

In [23]:
df

    Sepal Length  Sepal Width  Petal Length  Petal Width     Species
0            5.1          3.5           1.4          0.2      Setosa
1            4.9          3.0           1.4          0.2      Setosa
2            4.7          3.2           1.3          0.2      Setosa
3            4.6          3.1           1.5          0.2      Setosa
4            5.0          3.6           1.4          0.2      Setosa
5            7.0          3.2           4.7          1.4  Versicolor
6            6.4          3.2           4.5          1.5  Versicolor
7            6.9          3.1           4.9          1.5  Versicolor
8            5.5          2.3           4.0          1.3  Versicolor
9            6.5          2.8           4.6          1.5  Versicolor
10           6.3          3.3           6.0          2.5   Virginica
11           5.8          2.7           5.1          1.9   Virginica
12           7.1          3.0           5.9          2.1   Virginica
13           6.3          2.9           5.6          1.8   Virginica
14           6.5          3.0           5.8          2.2   Virginica

In [24]:
data = df.drop(columns=['Petal Length', 'Petal Width'])

In [25]:
data

    Sepal Length  Sepal Width     Species
0            5.1          3.5      Setosa
1            4.9          3.0      Setosa
2            4.7          3.2      Setosa
3            4.6          3.1      Setosa
4            5.0          3.6      Setosa
5            7.0          3.2  Versicolor
6            6.4          3.2  Versicolor
7            6.9          3.1  Versicolor
8            5.5          2.3  Versicolor
9            6.5          2.8  Versicolor
10           6.3          3.3   Virginica
11           5.8          2.7   Virginica
12           7.1          3.0   Virginica
13           6.3          2.9   Virginica
14           6.5          3.0   Virginica